name: build windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: Jimver/cuda-toolkit@v0.2.9
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        method: 'network'
        sub-packages: '["nvcc"]'
    - name: Install and setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install
      shell: cmd

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg install boost:x64-windows
        .\vcpkg\vcpkg install opencv4[core]:x64-windows
      shell: cmd

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
