name: build windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: Jimver/cuda-toolkit@v0.2.9
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        method: 'network'
        sub-packages: '["nvcc"]'
        
    - name: Install dependencies
      run: |
        choco install boost-msvc-14.2
        choco install opencv
      shell: powershell
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}